### ISSUE TITLE
Fails if sudo is not available

### ISSUE THREAD

**Issue by TMLutas** [tytek2012/Portia_Installer_Script#2]
Turnkey Linux LAPP virtual machine does not include sudo out of the box. The script does not work as intended when that happens. 

Suggestion, add in something like the following so the script informatively fails

CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
if [ ${CAN_I_RUN_SUDO} -gt 0 ]
then
    echo "I can run the sudo command"
else
    echo "I can't run the Sudo command"
fi

code pulled from:
http://superuser.com/questions/195781/sudo-is-there-a-command-to-check-if-i-have-sudo-and-or-how-much-time-is-left

**Comment by tytek2012** [comment]
thanks I added it,

**Comment by TMLutas** [comment]
Thanks, that should give a clue for right now, and later on it can be made more sophisticated (like installing sudo if it isn't already installed).
